version: 1.0.{build}
environment:
  NUGET_SOURCE: https://www.myget.org/F/punchclock/api/v2
  NUGET_APIKEY:
    secure: YP/3KxC2ffsuHNaolPXj66JVGzSjON9FcR2S2OEzn9c6SV14oPzUh1ySyeT+G+aA
build_script:
- ps: >-
    ./build.cmd
test: off
artifacts:
- path: '**/bin/*'
- path: artifacts/*